name: API Reference

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.0.5
      - name: Set up Haxelib dependencies
        run: |
          haxelib install lime 7.8.0 --quiet
          haxelib install openfl 8.9.7 --quiet
          haxelib install dox --quiet
          haxelib dev moonshine-openfl-language-client $GITHUB_WORKSPACE
      - name: Build API reference
        working-directory: docs
        run: haxe docs.hxml
      - uses: actions/upload-artifact@v3
        with:
          name: moonshine-openfl-language-client-api-reference
          path: bin/api/
          if-no-files-found: error
      - name: Upload Site
        if: ${{ github.repository_owner == 'Moonshine-IDE' && github.event_name != 'pull_request' && github.ref_name == 'master' }}
        uses: JamesIves/github-pages-deploy-action@v4.2.3
        with:
          branch: gh-pages
          folder: bin/api/
