name: Flash

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.0.5
      - name: Set up Haxelib dependencies
        run: |
          haxelib install lime 7.8.0 --quiet
          haxelib install openfl 8.9.7 --quiet
          haxelib dev moonshine-openfl-language-client $GITHUB_WORKSPACE
      - name: Build Flash .swc library
        run: haxelib run openfl build flash -debug
      - uses: actions/upload-artifact@v3
        with:
          name: moonshine-openfl-language-client-flash
          path: |
            bin/flash/bin/*.swc
            src/
            README.md
            LICENSE
          if-no-files-found: error
